site_name: Hackland Docs
nav:
  - Intro: intro.md
# - Home: index.md
  - Tools:
    - Tools:      'tools/index.md'
    - CNC-CAD:    'tools/cnc/cad.md'
    - CNC-CAM:    'tools/cnc/cam.md'
    - CNC-MC:     'tools/cnc/machine.md'
  - About:
    - Hackland: 'about/hackland.md'
    - Contrib:  'about/contributing.md'


#theme: 'material'
