site_name: Hackland Docs
nav:
  - Tools:
    - CNC-CAD:    'tools/cnc/cad.md'
    - CNC-CAM:    'tools/cnc/cam.md'
    - CNC-MC:     'tools/cnc/machine.md'
  - About:
    - Hackland: 'about/hackland.md'
    - 'Hackland Docs':  'about/docs.md'


#theme: 'material'
